const actionTypes = {
  REFRESH_BOOKLIST: 'REFRESH_BOOKLIST',
  TOGGLE_READ: 'TOGGLE_READ',
  EDIT_BOOK: 'EDIT_BOOK',
  CHANGE_BOOK_VIEW: 'CHANGE_BOOK_VIEW',
  SET_FILTER: 'SET_FILTER',
  TOGGLE_ALL: 'TOGGLE_ALL',
  SEND_SEARCH_VALUE: 'SEND_SEARCH_VALUE'
};

export default actionTypes;